### ISSUE TITLE
Passing variable by LolApi.Summoner.getByName

### ISSUE THREAD

**Issue by tsvetant** [claudiowilson/LeagueJS#47]
Hey fellas, [not really an issue]
can you tell me what should I do to pass and change my response variable by `LolApi.Summoner.getByName`. I am not really sure what's wrong.

---
    var myresponse = "";
    LolApi.Summoner.getByName(summonerId, region, function(err, summoner) {
        .. 
        myresponse = "Name" 
        ..
    }
    log(myresponse) // not changed

I tried running through the code but there are stuff I am not familiar with.

**Comment by EldoranDev** [comment]
This is really not an issue, you should look into the callback  nature of NodeJS.

Your variable myresponse is altered but after you are logging the variable to the stdout.
Your callback function will be called by getByName when it finishes to fetch ne name, but because of its non blocking nature nodejs will allready execute code that is after the getByName call.

Hope my answer is some kind of a help for you.

But still I vote for closing this "issue" because it is in fact not an issue.

**Comment by tsvetant** [comment]
Yea I said it's not really an issue, but still asked since it might be interesting for someone else as well. I didn't quite understand, but I think I got the basics.
