### ISSUE TITLE
API requests occur in parallel instead of simultaneously

### ISSUE THREAD

**Issue by rinkelm** [claudiowilson/LeagueJS#62]
This might not be a bug (perhaps it's intentional) but requests made through leagueJS are in parallel. The following code demonstrates how it returns them sequentially. It takes roughly 750 ms per match request (7500 ms total) before this code will finish, but with BlueBird requests I was able to retrieve data from these 10 games in 750 ms total. 

```
'use strict';

var LolApi = require("leagueapi");
LolApi.init("XXXXXXXXXXXXXXXX", "na");

var region = "na";
var match_ids = [2363807729,2363820701,2363800381,
                2363736440,2363678033,2362867453,
                2362834895,2362663001, 2362488529,
                2362481597];

function getMatch(match_id, x){
  return LolApi.getMatch(match_id,true,region)
  .then(function(match){
    console.log("Match", x,  "Returned");
    return match;
  }).catch(function(err){
    console.log("Match", x,  "Failed:", err);
    getMatch(match_id, x);
  });
}

function promiseAll(){
  console.time("Time to Get Matches");
  var match_promises = [];
  for(var x in match_ids){
    match_promises.push(getMatch(match_ids[x],x));
  }
  Promise.all(match_promises).then(function(data){
    console.log("All Matches Finished");
    console.timeEnd("Time to Get Matches");
  }).catch(function(err){
    console.log(err);
  });
}

function main(){
  promiseAll();
}

main();

```

**Comment by twillard** [comment]
Looking at the code I believe this is due to the rate limiter implementation.  The way it attempts to make the rates smooth across the entire interval by default and using millisecond granularity causes two main issues:

1) it's really aggressive as soon as you start adding requests and starts rate-limiting almost immediately
2) because it relies on polling using a timer, this compounds the error a bit

These two issues seem to combine to cause the rate-limiter to severely over-limit requests.

This could be solved in part by allowing the user to specify the 'allowbursts' parameter when calling LoLApi.setRateLimit

**Comment by twillard** [comment]
Actually nevermind about the rate limiter being "Wrong" - I just misinterpreted a couple things.  It's slightly inefficient but not enough to cause problems.  I think we were just setting our "rate per 10m" too low
