### ISSUE TITLE
Riot API v2 doesn't work anymore...

### ISSUE THREAD

**Issue by alexbourl** [claudiowilson/LeagueJS#70]
Will you update the LeagueJS?
Or we should change library?? :"(

**Comment by claudiowilson** [comment]
The refactor is happening here: thanks to @Colorfulstan hang tight! https://github.com/claudiowilson/LeagueJS/pull/65

**Comment by Colorfulstan** [comment]
It won't be backwards compatible since I basically worked on it alone and...didn't feel like it I guess ;)
No seriously, did not have the time to think about that too.

So have a look at the new Quickstart, Im basically just waiting for maintainer approval to get it published.
We will update here when done I think.

Also related to #64

**Comment by alexbourl** [comment]
Thank you very much guys!!

**Comment by Colorfulstan** [comment]
I did publish my fork (the rework) under "leaguejs" on npm if you want to check it out.
Since it's not backwards compatible you might need to evaluate if the switch is worth it for you, or if you want to check out https://www.npmjs.com/package/kindred-api which is more elaborate then leagueJS and the upcoming go to library for node I think

**Comment by Colorfulstan** [comment]
rework is published to [npm](https://www.npmjs.com/package/leaguejs)
